name: Render
run-name: Render

on:
  push:
    branches:
      - main
    paths-ignore:
      - .gitignore
      - README*
      - .github/**
      - "!.github/workflows/render.yml"
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Setup Typst
        uses: typst-community/setup-typst@v4
        with:
          cache-dependency-path: config.typ

      - run: typst --version

      - name: Create compiled directory
        run: mkdir -p compiled

      - name: Compile Typst to PDF
        run: typst compile seL4.typ compiled/seL4.pdf

      - name: Commit and push changes
        uses: devops-infra/action-commit-push@master
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          commit_message: "Update compiled PDF"
          branch: main
          files: "compiled/seL4.pdf"
        continue-on-error: true