name: Render
run-name: Render

on:
  push:
    branches:
      - main
    paths-ignore:
      - .gitignore
      - README*
      - .github/**
      - "!.github/workflows/render.yml"
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Typst
        uses: typst-community/setup-typst@v4
        with:
          cache-dependency-path: config.typ

      - run: typst --version
      - run: typst compile seL4.typ

      - name: Upload PDFs as artifact
        uses: actions/upload-artifact@v4
        with:
          name: PDF
          path: "*.pdf"